apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: gnekouzita/udagram-api-user
        ports:
        - containerPort: 3001
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: aws-secret
        