apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: gnekouzita/udagram-api-feed
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: env-secret
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: aws-secret
        
